#!/usr/bin/env ruby

$: << File.dirname(__FILE__) + "/../lib"
require 'pathname'

def include_directory(dir) 
  dir.each_entry do |entry|
    next if entry.to_s=~ /^\./
    if (dir + entry).directory?
      include_directory(dir + entry)      
      next
    end
    next unless entry.to_s=~ /^tc_.+\.rb$/
    
    load dir + entry
  end
end

include_directory(Pathname.new(__FILE__).dirname)
